### ISSUE TITLE
Use a local repo

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/tattoo#12] opened 2016-04-25 20:01 UTC
Right now developers have to push to github, then use a branch config to pull it back down.

The branch config should just take paths, like so:

``` json
{
  "branch-config": {
    "paper-button" : "/Users/justinfagnani/code/paper-button"
  },
}
```

**Comment by usergenic** [comment] 2016-11-18 23:04
Obsolete config example and now duplicate of #23

**Closed by usergenic** 2016-11-18 23:04 UTC
